version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: bnhf/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    depends_on:
      - "gui"
    volumes:
     - ./openvpn-data/conf:/etc/openvpn
  gui:
    image: bnhf/openvpn-tap-external-web-ui
    container_name: openvpn-gui
    environment:
    - OPENVPN_ADMIN_USERNAME=admin
    - OPENVPN_ADMIN_PASSWORD=b3secure
    - COUNTRY=${COUNTRY}
    - PROVINCE=G${PROVINCE}
    - CITY=${CITY}
    - ORG=${ORG}
    - EMAIL=${EMAIL}
    - OU=${OU}
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - /etc/openvpn:/etc/openvpn
     - ./openvpn-data/db:/opt/openvpn-gui/db
